export enum PackingTypeEnum {
  CARTONS = "Cartons",
  BAGS = "Bags",
  BALES = "Bales",
  BARRELS = "Barrels",
  BOXES = "Boxes",
  BUNDLES = "Bundles",
  COILS = "Coils",
  CONTAINERS = "Containers",
  CRATES = "Crates",
  ROLLS = "Rolls",
  SKIDS = "Skids",
  TOTES = "Totes",
  OTHER = "Other",
}
