export const mockQuote = {
  type: "FTL",
  shipment: {
    commodity: "Plastic bales",
    emergency_name: "dssdfsdfs",
    emergency_phone: "12312313232",
    emergency_phone2: "",
    goods_value: "233233323",
    hazardous_goods: "yes",
    packing_method: "PALLETIZED",
    packing_type: "Unknown",
    quantity: "2323",
    reference_no0: "34242342",
    reference_no1: "66456666",
    reference_no2: "767676767",
    special_instructions:
      "Prioritize safety by adhering to established protocols for FTL travel. Regular maintenance of FTL drives and thorough training " +
      "for personnel are essential.Prioritize safety by adhering to established protocols for FTL travel. Regular maintenance of FTL " +
      "drives and thorough training for personnel are essential.",
    un_id_number: "132131313",
    weight: "231313",
    weight_type: "LB",
    equipment_type: "reefer",
    max_temp_reefer: "10",
    min_temp_reefer: "-5",
    straps: "on",
    team_drivers: "on",
    frozen: "on",
  },
  pickup: [
    {
      LAF: "on",
      LGDR: "on",
      addTime: "no",
      address: "Miami Beach , MI12323",
      date: "2024-08-02",
      deliveryLocationType: "Business",
      locationNotes: "Astarojna cum dai zadnea la intrare",
      locationTimeStart: "any",
      shippingHoursType: "BY_APPOINTMENT",
    },
    {
      addTime: "yes",
      address: "Boulverdul Dacia 112/1 , MD9999",
      date: "2024-08-02",
      deliveryLocationType: "Business",
      locationNotes: "",
      locationTimeStart: "Any time during business hours",
      shippingHoursType: "BY_APPOINTMENT",
    },
    {
      addTime: "yes",
      address: "str. Zadnipru 69/69 ",
      date: "2024-08-02",
      deliveryLocationType: "Business",
      locationNotes: "Suna din timp",
      locationTimeStart: "5:30 AM",
      locationTimeEnd: "8:30 AM",
      shippingHoursType: "BY_APPOINTMENT",
    },
    {
      addTime: "no",
      address: "str. Zadnipru 69/69 ",
      date: "2024-08-02",
      deliveryLocationType: "Business",
      locationNotes: "",
      locationTimeStart: "5:30 AM",
      locationTimeEnd: "8:30 AM",
      shippingHoursType: "BY_APPOINTMENT",
    },
  ],

  drop: [
    {
      LAF: "on",
      LGDR: "on",
      addTime: "no",
      address: "Miami Beach , MI12323",
      date: "2024-08-02",
      deliveryLocationType: "Business",
      locationNotes: "Astarojna cum dai zadnea la intrare",
      locationTimeStart: "any",
      shippingHoursType: "BY_APPOINTMENT",
    },
    {
      addTime: "yes",
      address: "Boulverdul Dacia 112/1 , MD9999",
      date: "2024-08-02",
      deliveryLocationType: "Business",
      locationNotes: "",
      locationTimeStart: "Any time during business hours",
      shippingHoursType: "BY_APPOINTMENT",
    },
    {
      addTime: "yes",
      address: "str. Zadnipru 69/69 ",
      date: "2024-08-02",
      deliveryLocationType: "Business",
      locationNotes: "Suna din timp",
      locationTimeStart: "5:30 AM",
      locationTimeEnd: "8:30 AM",
      shippingHoursType: "BY_APPOINTMENT",
    },
    {
      addTime: "no",
      address: "str. Zadnipru 69/69 ",
      date: "2024-08-02",
      deliveryLocationType: "Business",
      locationNotes: "",
      locationTimeStart: "5:30 AM",
      locationTimeEnd: "8:30 AM",
      shippingHoursType: "BY_APPOINTMENT",
    },
  ],
};
