import { PartnerI } from "@/app/get-quote/pages/partners/components/partners-table.component";

export const partnersMock: PartnerI[] = [
  {
    company: "Ship Fortus LTD",
    contact: "Ion Ioxa",
    email: "info@shipfortus.com",
    location: "Detroit , MI 12345",
    tags: ["Ocean", "FTL", "LTL"],
  },
  {
    company: "Ship Fortus LTD",
    contact: "Ion Ioxa",
    email: "info@shipfortus.com",
    location: "Detroit , MI 12345",
    tags: ["Ocean", "FTL", "LTL"],
  },
  {
    company: "Ship Test Fortus Test LTD",
    contact: "Abba Obba Ebba Los",
    email: "info@shiptesttestfortus.com",
    location: "Detroit , MI 123451231231",
    tags: [
      "Ocean",
      "FTL",
      "LTL",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
    ],
  },
  {
    company: "Ship Test Fortus Test LTD",
    contact: "Abba Obba Ebba Los",
    email: "info@shiptesttestfortus.com",
    location: "Detroit , MI 123451231231",
    tags: [
      "Ocean",
      "FTL",
      "LTL",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
    ],
  },
  {
    company: "Ship Fortus LTD",
    contact: "Ion Ioxa",
    email: "info@shipfortus.com",
    location: "Detroit , MI 12345",
    tags: ["Ocean", "FTL", "LTL"],
  },
  {
    company: "Ship Fortus LTD",
    contact: "Ion Ioxa",
    email: "info@shipfortus.com",
    location: "Detroit , MI 12345",
    tags: ["Ocean", "FTL", "LTL"],
  },
  {
    company: "Ship Test Fortus Test LTD",
    contact: "Abba Obba Ebba Los",
    email: "info@shiptesttestfortus.com",
    location: "Detroit , MI 123451231231",
    tags: [
      "Ocean",
      "FTL",
      "LTL",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
    ],
  },
  {
    company: "Ship Test Fortus Test LTD",
    contact: "Abba Obba Ebba Los",
    email: "info@shiptesttestfortus.com",
    location: "Detroit , MI 123451231231",
    tags: [
      "Ocean",
      "FTL",
      "LTL",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
    ],
  },
  {
    company: "Ship Fortus LTD",
    contact: "Ion Ioxa",
    email: "info@shipfortus.com",
    location: "Detroit , MI 12345",
    tags: ["Ocean", "FTL", "LTL"],
  },
  {
    company: "Ship Fortus LTD",
    contact: "Ion Ioxa",
    email: "info@shipfortus.com",
    location: "Detroit , MI 12345",
    tags: ["Ocean", "FTL", "LTL"],
  },
  {
    company: "Ship Test Fortus Test LTD",
    contact: "Abba Obba Ebba Los",
    email: "info@shiptesttestfortus.com",
    location: "Detroit , MI 123451231231",
    tags: [
      "Ocean",
      "FTL",
      "LTL",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
    ],
  },
  {
    company: "Ship Test Fortus Test LTD",
    contact: "Abba Obba Ebba Los",
    email: "info@shiptesttestfortus.com",
    location: "Detroit , MI 123451231231",
    tags: [
      "Ocean",
      "FTL",
      "LTL",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
    ],
  },
  {
    company: "Ship Fortus LTD",
    contact: "Ion Ioxa",
    email: "info@shipfortus.com",
    location: "Detroit , MI 12345",
    tags: ["Ocean", "FTL", "LTL"],
  },
  {
    company: "Ship Fortus LTD",
    contact: "Ion Ioxa",
    email: "info@shipfortus.com",
    location: "Detroit , MI 12345",
    tags: ["Ocean", "FTL", "LTL"],
  },
  {
    company: "Ship Test Fortus Test LTD",
    contact: "Abba Obba Ebba Los",
    email: "info@shiptesttestfortus.com",
    location: "Detroit , MI 123451231231",
    tags: [
      "Ocean",
      "FTL",
      "LTL",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
    ],
  },
  {
    company: "Ship Test Fortus Test LTD",
    contact: "Abba Obba Ebba Los",
    email: "info@shiptesttestfortus.com",
    location: "Detroit , MI 123451231231",
    tags: [
      "Ocean",
      "FTL",
      "LTL",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
    ],
  },
  {
    company: "Ship Fortus LTD",
    contact: "Ion Ioxa",
    email: "info@shipfortus.com",
    location: "Detroit , MI 12345",
    tags: ["Ocean", "FTL", "LTL"],
  },
  {
    company: "Ship Fortus LTD",
    contact: "Ion Ioxa",
    email: "info@shipfortus.com",
    location: "Detroit , MI 12345",
    tags: ["Ocean", "FTL", "LTL"],
  },
  {
    company: "Ship Test Fortus Test LTD",
    contact: "Abba Obba Ebba Los",
    email: "info@shiptesttestfortus.com",
    location: "Detroit , MI 123451231231",
    tags: [
      "Ocean",
      "FTL",
      "LTL",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
    ],
  },
  {
    company: "Ship Test Fortus Test LTD",
    contact: "Abba Obba Ebba Los",
    email: "info@shiptesttestfortus.com",
    location: "Detroit , MI 123451231231",
    tags: [
      "Ocean",
      "FTL",
      "LTL",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
    ],
  },
  {
    company: "Ship Fortus LTD",
    contact: "Ion Ioxa",
    email: "info@shipfortus.com",
    location: "Detroit , MI 12345",
    tags: ["Ocean", "FTL", "LTL"],
  },
  {
    company: "Ship Fortus LTD",
    contact: "Ion Ioxa",
    email: "info@shipfortus.com",
    location: "Detroit , MI 12345",
    tags: ["Ocean", "FTL", "LTL"],
  },
  {
    company: "Ship Test Fortus Test LTD",
    contact: "Abba Obba Ebba Los",
    email: "info@shiptesttestfortus.com",
    location: "Detroit , MI 123451231231",
    tags: [
      "Ocean",
      "FTL",
      "LTL",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
    ],
  },
  {
    company: "Ship Test Fortus Test LTD",
    contact: "Abba Obba Ebba Los",
    email: "info@shiptesttestfortus.com",
    location: "Detroit , MI 123451231231",
    tags: [
      "Ocean",
      "FTL",
      "LTL",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
      "Test",
    ],
  },
];
