export const mockBids = [
  {
    company: "ABC Logistics",
    status: "expired",
    date: "Mar 12,2024",
    estimatedPerMile: "6$",
    totalMiles: "1800",
    price: 4200,
    id: "66d880acb5f5fa70b799515f",
    transitTime: 30,
    email: "info@abclogistics.com",
    notes: "Looking forward to potential collaboration for freight transport.",
  },
  {
    company: "Fortus Group",
    status: "active",
    date: "Apr 07,2024",
    estimatedPerMile: "12$",
    totalMiles: "3000",
    price: 8000,
    id: "0008",
    transitTime: 110,
    email: "contact@fortusgroup.com",
    notes: "Discussing new transportation strategies for the upcoming quarter.",
  },
  {
    company: "Test Group",
    status: "active",
    date: "Jan 15,2024",
    estimatedPerMile: "8$",
    totalMiles: "2000",
    price: 6000,
    transitTime: 25,
    email: "support@testgroup.com",
    notes: "Proposal for long-term transportation collaboration.",
    id: "0020",
  },
  {
    company: "Fortus Group",
    status: "expired",
    date: "Feb 26,2024",
    transitTime: 14,
    email: "info@fortusgroup.com",
    estimatedPerMile: "7$",
    notes: "Potential collaboration for freight transport.",
    totalMiles: "2457",
    price: 5000,
    id: "0014",
  },
  {
    company: "Test Group",
    transitTime: 1,
    status: "active",
    date: "May 18,2024",
    email: "contact@testgroup.com",
    estimatedPerMile: "9$",
    totalMiles: "2200",
    price: 6500,
    id: "0016",
  },
  {
    company: "ABC Logistics",
    transitTime: 3,
    notes: "Exploring new freight transport routes.",
    email: "support@abclogistics.com",
    status: "active",
    date: "Jun 21,2024",
    estimatedPerMile: "5$",
    totalMiles: "2400",
    price: 3600,
    id: "0011",
  },
  {
    company: "Fortus Group",
    email: "contact@fortusgroup.com",
    notes: "Discussing potential transportation opportunities.",
    transitTime: 5,
    status: "active",
    date: "Jul 10,2024",
    estimatedPerMile: "10$",
    totalMiles: "2457",
    price: 7000,
    id: "0002",
  },
  {
    company: "Test Group",
    notes: "Freight transport proposal for our clients.",
    email: "info@testgroup.com",
    status: "expired",
    transitTime: 90,
    date: "Aug 05,2024",
    estimatedPerMile: "4$",
    totalMiles: "2457",
    price: 2500,
    id: "0017",
  },
  {
    email: "contact@abclogistics.com",
    notes: "Exploring collaboration for freight transport.",
    company: "ABC Logistics",
    transitTime: 27,
    status: "active",
    date: "Sep 11,2024",
    estimatedPerMile: "3$",
    totalMiles: "2500",
    price: 1900,
    id: "0010",
  },
  {
    email: "support@fortusgroup.com",
    company: "Fortus Group",
    status: "active",
    transitTime: 11,
    date: "Oct 19,2024",
    estimatedPerMile: "10$",
    totalMiles: "2457",
    price: 7000,
    id: "0006",
  },
  {
    email: "info@testgroup.com",
    notes: "Proposal for transportation collaboration.",
    company: "Test Group",
    transitTime: 9,
    status: "expired",
    date: "Nov 26,2024",
    estimatedPerMile: "4$",
    totalMiles: "2457",
    price: 2500,
    id: "0019",
  },
  {
    email: "support@abclogistics.com",
    company: "ABC Logistics",
    transitTime: 10,
    notes: "Potential for collaboration in freight transport.",
    status: "active",
    date: "Dec 31,2024",
    estimatedPerMile: "3$",
    totalMiles: "2457",
    price: 1799,
    id: "0013",
  },
];
