import {
  QuoteAddressI,
  QuotePreviewI,
} from "@/common/interfaces/quote-preview.interface";
import { QuoteStatusEnum } from "@/common/enums/quote-status.enum";
import { QuoteTypeEnum } from "@/common/enums/quote-type.enum";

const address1: QuoteAddressI[] = [
  {
    address: "Clinton, IA 45987",
    date: "Feb 26 7AM-5PM",
  },
];

const address2: QuoteAddressI[] = [
  {
    address: "Clinton Clinton, IA 45987",
    date: "Feb 26 7AM-5PM",
  },
  {
    address: "Clinton, IA 45987",
    date: "Feb 26 7AM-5PM",
  },
];

const address3: QuoteAddressI[] = [
  {
    address: "Clinton, IA 45987",
    date: "Feb 26 7AM-5PM",
  },
  {
    address: "Clinton, IA 45987",
    date: "Feb 26 7AM-5PM",
  },
  {
    address: "Clinton, IA 45987",
    date: "Feb 26 7AM-5PM",
  },
];

export const mockData: QuotePreviewI[] = [
  {
    id: "001723",
    status: QuoteStatusEnum.REQUESTED,
    pickupAddress: address1,
    dropAddress: address2,
    ref: "000145890",
    refDetails: "Value: $35,000, Live Load",
    equipment: "53’ Dryvan ,53’ Reefer",
    currency: "USD",
    price: 1300,
    weight: 35000,
    weightDetails: "Paper Rolls / Floor Loaded",
    type: QuoteTypeEnum.FTL,
  },
  {
    id: "001724",
    status: QuoteStatusEnum.CONFIRMED,
    pickupAddress: address3,
    dropAddress: address1,
    ref: "000145890",
    refDetails: "Value: $35,000, Live Load",
    equipment: "53’ Dryvan ,53’ Reefer",
    currency: "USD",
    price: 7777,
    weight: 20000,
    weightDetails: "Paper Rolls / Floor Loaded",
    type: QuoteTypeEnum.FTL,
  },
  {
    id: "001725",
    status: QuoteStatusEnum.BOOKED,
    pickupAddress: address2,
    dropAddress: [...address2, ...address3],
    ref: "000145890",
    refDetails: "Value: $35,000, Live Load",
    equipment: "53’ Dryvan ,53’ Reefer",
    currency: "USD",
    price: 99999,
    weight: 35000,
    weightDetails: "Paper Rolls / Floor Loaded",
    type: QuoteTypeEnum.FTL,
  },

  {
    id: "001723",
    status: QuoteStatusEnum.REQUESTED,
    pickupAddress: address1,
    dropAddress: address2,
    ref: "000145890",
    refDetails: "Value: $35,000, Live Load",
    equipment: "53’ Dryvan ,53’ Reefer",
    currency: "USD",
    price: 1300,
    weight: 35000,
    weightDetails: "Paper Rolls / Floor Loaded",
    type: QuoteTypeEnum.FTL,
  },
  {
    id: "001724",
    status: QuoteStatusEnum.CONFIRMED,
    pickupAddress: address3,
    dropAddress: address1,
    ref: "000145890",
    refDetails: "Value: $35,000, Live Load",
    equipment: "53’ Dryvan ,53’ Reefer",
    currency: "USD",
    price: 7777,
    weight: 20000,
    weightDetails: "Paper Rolls / Floor Loaded",
    type: QuoteTypeEnum.FTL,
  },
  {
    id: "001725",
    status: QuoteStatusEnum.BOOKED,
    pickupAddress: address2,
    dropAddress: [...address2, ...address3],
    ref: "000145890",
    refDetails: "Value: $35,000, Live Load",
    equipment: "53’ Dryvan ,53’ Reefer",
    currency: "USD",
    price: 99999,
    weight: 35000,
    weightDetails: "Paper Rolls / Floor Loaded",
    type: QuoteTypeEnum.FTL,
  },

  {
    id: "001723",
    status: QuoteStatusEnum.REQUESTED,
    pickupAddress: address1,
    dropAddress: address2,
    ref: "000145890",
    refDetails: "Value: $35,000, Live Load",
    equipment: "53’ Dryvan ,53’ Reefer",
    currency: "USD",
    price: 1300,
    weight: 35000,
    weightDetails: "Paper Rolls / Floor Loaded",
    type: QuoteTypeEnum.FTL,
  },
  {
    id: "001724",
    status: QuoteStatusEnum.CONFIRMED,
    pickupAddress: address3,
    dropAddress: address1,
    ref: "000145890",
    refDetails: "Value: $35,000, Live Load",
    equipment: "53’ Dryvan ,53’ Reefer",
    currency: "USD",
    price: 7777,
    weight: 20000,
    weightDetails: "Paper Rolls / Floor Loaded",
    type: QuoteTypeEnum.FTL,
  },
  {
    id: "001725",
    status: QuoteStatusEnum.BOOKED,
    pickupAddress: address2,
    dropAddress: [...address2, ...address3],
    ref: "000145890",
    refDetails: "Value: $35,000, Live Load",
    equipment: "53’ Dryvan ,53’ Reefer",
    currency: "USD",
    price: 99999,
    weight: 35000,
    weightDetails: "Paper Rolls / Floor Loaded",
    type: QuoteTypeEnum.FTL,
  },
  {
    id: "001723",
    status: QuoteStatusEnum.REQUESTED,
    pickupAddress: address1,
    dropAddress: address2,
    ref: "000145890",
    refDetails: "Value: $35,000, Live Load",
    equipment: "53’ Dryvan ,53’ Reefer",
    currency: "USD",
    price: 1300,
    weight: 35000,
    weightDetails: "Paper Rolls / Floor Loaded",
    type: QuoteTypeEnum.FTL,
  },
  {
    id: "001724",
    status: QuoteStatusEnum.CONFIRMED,
    pickupAddress: address3,
    dropAddress: address1,
    ref: "000145890",
    refDetails: "Value: $35,000, Live Load",
    equipment: "53’ Dryvan ,53’ Reefer",
    currency: "USD",
    price: 7777,
    weight: 20000,
    weightDetails: "Paper Rolls / Floor Loaded",
    type: QuoteTypeEnum.FTL,
  },
  {
    id: "001725",
    status: QuoteStatusEnum.BOOKED,
    pickupAddress: address2,
    dropAddress: [...address2, ...address3],
    ref: "000145890",
    refDetails: "Value: $35,000, Live Load",
    equipment: "53’ Dryvan ,53’ Reefer",
    currency: "USD",
    price: 99999,
    weight: 35000,
    weightDetails: "Paper Rolls / Floor Loaded",
    type: QuoteTypeEnum.FTL,
  },
];
